// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-4)
// protocol is simulatable under MLWE(36,25,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(13,101,2^(34.193812))
// 
// Ring
// degree d = 64
// modulus q = 72057594037928981, log(q) ~ 56.0
// factors q = q1
// 
// Compression
// D = 10
// gamma = 440390, log(gamma) ~ 18.748422
// 
// Dimensions of secrets
// s1: m1 = 40
// m: l = 0
// s2: m2 = 61
// 
// Size of secrets
// l2(s1) <= alpha = 130.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 12)
// exact euclidean: yes (dimensions: [8, 8, 12], bounds: [67.882251, 67.882251, 83.138439])
// approximate infinity: yes (psi: 4135.3611, dimension: 20, bound: 106417.7)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 203161.6, log(stdev1/1.55) = 17.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 12697.6, log(stdev3/1.55) = 13.0
// stdev4 = 13002342.4, log(stdev4/1.55) = 23.0
// 
// Repetition rate
// M1 = 3.3495694
// M2 = 2.5836129
// M3 = 1.018019
// M4 = 1.0113511
// total = 8.9099297
// 
// Security
// MSIS dimension: 13
// MSIS root hermite factor: 1.0043581
// MLWE dimension: 36
// MLWE root hermite factor: 1.0042899
// 
// Proof size
// ~ 25.7050781250000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t _param_q_limbs[] = {72057594037928981UL};
static const int_t _param_q = {{(limb_t *)_param_q_limbs, 1, 0}};
static const limb_t _param_qminus1_limbs[] = {72057594037928980UL};
static const int_t _param_qminus1 = {{(limb_t *)_param_qminus1_limbs, 1, 0}};
static const limb_t _param_m_limbs[] = {163622230382UL};
static const int_t _param_m = {{(limb_t *)_param_m_limbs, 1, 0}};
static const limb_t _param_mby2_limbs[] = {81811115191UL};
static const int_t _param_mby2 = {{(limb_t *)_param_mby2_limbs, 1, 0}};
static const limb_t _param_gamma_limbs[] = {440390UL};
static const int_t _param_gamma = {{(limb_t *)_param_gamma_limbs, 1, 0}};
static const limb_t _param_gammaby2_limbs[] = {220195UL};
static const int_t _param_gammaby2 = {{(limb_t *)_param_gammaby2_limbs, 1, 0}};
static const limb_t _param_pow2D_limbs[] = {1024UL};
static const int_t _param_pow2D = {{(limb_t *)_param_pow2D_limbs, 1, 0}};
static const limb_t _param_pow2Dby2_limbs[] = {512UL};
static const int_t _param_pow2Dby2 = {{(limb_t *)_param_pow2Dby2_limbs, 1, 0}};
static const limb_t _param_Bsq_limbs[] = {80639691163744UL, 0UL};
static const int_t _param_Bsq = {{(limb_t *)_param_Bsq_limbs, 2, 0}};
static const limb_t _param_scM1_limbs[] = {12482723293249251754UL, 6448417599017056673UL, 3UL};
static const int_t _param_scM1 = {{(limb_t *)_param_scM1_limbs, 3, 0}};
static const limb_t _param_scM2_limbs[] = {9426604441654671652UL, 10765757998783256511UL, 2UL};
static const int_t _param_scM2 = {{(limb_t *)_param_scM2_limbs, 3, 0}};
static const limb_t _param_scM3_limbs[] = {11004360535250222166UL, 332392564624599531UL, 1UL};
static const int_t _param_scM3 = {{(limb_t *)_param_scM3_limbs, 3, 0}};
static const limb_t _param_scM4_limbs[] = {6521313850603405929UL, 209390726442610011UL, 1UL};
static const int_t _param_scM4 = {{(limb_t *)_param_scM4_limbs, 3, 0}};
static const limb_t _param_stdev1sq_limbs[] = {41274635715UL, 0UL};
static const int_t _param_stdev1sq = {{(limb_t *)_param_stdev1sq_limbs, 2, 0}};
static const limb_t _param_stdev2sq_limbs[] = {40307261UL, 0UL};
static const int_t _param_stdev2sq = {{(limb_t *)_param_stdev2sq_limbs, 2, 0}};
static const limb_t _param_stdev3sq_limbs[] = {161229046UL, 0UL};
static const int_t _param_stdev3sq = {{(limb_t *)_param_stdev3sq_limbs, 2, 0}};
static const limb_t _param_stdev4sq_limbs[] = {169060907886838UL, 0UL};
static const int_t _param_stdev4sq = {{(limb_t *)_param_stdev4sq_limbs, 2, 0}};
static const limb_t _param_inv2_limbs[] = {36028797018964490UL};
static const int_t _param_inv2 = {{(limb_t *)_param_inv2_limbs, 1, 1}};
static const limb_t _param_inv4_limbs[] = {18014398509482245UL};
static const int_t _param_inv4 = {{(limb_t *)_param_inv4_limbs, 1, 1}};
static const unsigned int _param_n[3] = {8, 8, 12};
static const limb_t _param_Bz3sqr_limbs[] = {111012260217UL, 0UL};
static const int_t _param_Bz3sqr = {{(limb_t *)_param_Bz3sqr_limbs, 2, 0}};
static const limb_t _param_Bz4_limbs[] = {208037478UL};
static const int_t _param_Bz4 = {{(limb_t *)_param_Bz4_limbs, 1, 0}};
static const limb_t _param_Pmodq_limbs[] = {701738831619525UL};
static const int_t _param_Pmodq = {{(limb_t *)_param_Pmodq_limbs, 1, 0}};
static const limb_t _param_l2Bsq0_limbs[] = {4608UL};
static const int_t _param_l2Bsq0 = {{(limb_t *)_param_l2Bsq0_limbs, 1, 0}};
static const limb_t _param_l2Bsq1_limbs[] = {4608UL};
static const int_t _param_l2Bsq1 = {{(limb_t *)_param_l2Bsq1_limbs, 1, 0}};
static const limb_t _param_l2Bsq2_limbs[] = {6912UL};
static const int_t _param_l2Bsq2 = {{(limb_t *)_param_l2Bsq2_limbs, 1, 0}};
static const limb_t _param_Ppmodq_0_limbs[] = {16132034589193255UL};
static const int_t _param_Ppmodq_0 = {{(limb_t *)_param_Ppmodq_0_limbs, 1, 1}};
static const limb_t _param_Ppmodq_1_limbs[] = {16132034593679821UL};
static const int_t _param_Ppmodq_1 = {{(limb_t *)_param_Ppmodq_1_limbs, 1, 1}};
static const limb_t _param_Ppmodq_2_limbs[] = {16132034597843905UL};
static const int_t _param_Ppmodq_2 = {{(limb_t *)_param_Ppmodq_2_limbs, 1, 1}};
static const int_srcptr _param_l2Bsq[] = {_param_l2Bsq0, _param_l2Bsq1, _param_l2Bsq2};
static const int_srcptr _param_Ppmodq[] = {_param_Ppmodq_0, _param_Ppmodq_1, _param_Ppmodq_2};
static const polyring_t _param_ring = {{_param_q, 64, 57, 6, moduli_d64, 3, _param_Pmodq, _param_Ppmodq, _param_inv2}};
static const dcompress_params_t _param_dcomp = {{ _param_q, _param_qminus1, _param_m, _param_mby2, _param_gamma, _param_gammaby2, _param_pow2D, _param_pow2Dby2, 10, 0, 38 }};
static const abdlop_params_t _param_tbox = {{ _param_ring, _param_dcomp, 43, 61, 0, 12, 13, _param_Bsq, 1, 8, 5, 140, 1, 17, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_eval_ = {{ _param_ring, _param_dcomp, 43, 61, 9, 3, 13, _param_Bsq, 1, 8, 5, 140, 1, 17, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_many_ = {{ _param_ring, _param_dcomp, 43, 61, 11, 1, 13, _param_Bsq, 1, 8, 5, 140, 1, 17, _param_scM1, _param_stdev1sq, 2, 12, _param_scM2, _param_stdev2sq}};
static const lnp_quad_eval_params_t _param_quad_eval = {{ _param_quad_eval_, _param_quad_many_, 4}};
static const lnp_tbox_params_t _param = {{ _param_tbox, _param_quad_eval, 12, _param_n, 20, 3, 43, 2, 13, _param_scM3, _param_stdev3sq, 2, 23, _param_scM4, _param_stdev4sq, _param_Bz3sqr, _param_Bz4, &_param_l2Bsq[0], _param_inv4, 26322UL }};

static const unsigned int param_Ps[12] = {28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39};
static const unsigned int param_Es0[8] = {0, 1, 2, 3, 4, 5, 6, 7};
static const unsigned int param_Es1[8] = {8, 9, 10, 11, 12, 13, 14, 15};
static const unsigned int param_Es2[12] = {16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27};
static const unsigned int *param_Es[3] = { param_Es0, param_Es1, param_Es2, };
static const unsigned int param_Es_nrows[3] = {8, 8, 12};

static const limb_t param_p_limbs[] = {52027369UL};
static const int_t param_p = {{(limb_t *)param_p_limbs, 1, 0}};
static const limb_t param_pinv_limbs[] = {26962802864444717UL};
static const int_t param_pinv = {{(limb_t *)param_pinv_limbs, 1, 0}};
static const unsigned int param_s1_indices[40] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39};
static const lin_params_t param = {{ _param, 64, param_p, param_pinv, 1, param_s1_indices, 40, NULL, 0,  param_Ps, 12, param_Es, param_Es_nrows, NULL, NULL }};

