// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-4)
// protocol is simulatable under MLWE(32,32,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(20,96,2^(40.1892))
// 
// Ring
// degree d = 64
// modulus q = 1125899906843189, log(q) ~ 50.0
// factors q = q1
// 
// Compression
// D = 16
// gamma = 30988582, log(gamma) ~ 24.885233
// 
// Dimensions of secrets
// s1: m1 = 32
// m: l = 0
// s2: m2 = 64
// 
// Size of secrets
// l2(s1) <= alpha = 9204.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: no
// exact euclidean: yes (dimensions: [16, 16], bounds: [9203.0, 87.0])
// approximate infinity: yes (psi: 2988.9126, dimension: 8, bound: 9423105.6)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 13002342.4, log(stdev1/1.55) = 23.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 812646.4, log(stdev3/1.55) = 19.0
// stdev4 = 832149913.6, log(stdev4/1.55) = 29.0
// 
// Repetition rate
// M1 = 3.7817448
// M2 = 2.707079
// M3 = 1.0218472
// M4 = 1.0218416
// total = 10.689631
// 
// Security
// MSIS dimension: 20
// MSIS root hermite factor: 1.0043828
// MLWE dimension: 32
// MLWE root hermite factor: 1.0043146
// 
// Proof size
// ~ 25.8593750000000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t _blns_param_q_limbs[] = {1125899906843189UL};
static const int_t _blns_param_q = {{(limb_t *)_blns_param_q_limbs, 1, 0}};
static const limb_t _blns_param_qminus1_limbs[] = {1125899906843188UL};
static const int_t _blns_param_qminus1 = {{(limb_t *)_blns_param_qminus1_limbs, 1, 0}};
static const limb_t _blns_param_m_limbs[] = {36332734UL};
static const int_t _blns_param_m = {{(limb_t *)_blns_param_m_limbs, 1, 0}};
static const limb_t _blns_param_mby2_limbs[] = {18166367UL};
static const int_t _blns_param_mby2 = {{(limb_t *)_blns_param_mby2_limbs, 1, 0}};
static const limb_t _blns_param_gamma_limbs[] = {30988582UL};
static const int_t _blns_param_gamma = {{(limb_t *)_blns_param_gamma_limbs, 1, 0}};
static const limb_t _blns_param_gammaby2_limbs[] = {15494291UL};
static const int_t _blns_param_gammaby2 = {{(limb_t *)_blns_param_gammaby2_limbs, 1, 0}};
static const limb_t _blns_param_pow2D_limbs[] = {65536UL};
static const int_t _blns_param_pow2D = {{(limb_t *)_blns_param_pow2D_limbs, 1, 0}};
static const limb_t _blns_param_pow2Dby2_limbs[] = {32768UL};
static const int_t _blns_param_pow2Dby2 = {{(limb_t *)_blns_param_pow2Dby2_limbs, 1, 0}};
static const limb_t _blns_param_Bsq_limbs[] = {517023324650225917UL, 0UL};
static const int_t _blns_param_Bsq = {{(limb_t *)_blns_param_Bsq_limbs, 2, 0}};
static const limb_t _blns_param_scM1_limbs[] = {16834934180896570668UL, 14420645696602552791UL, 3UL};
static const int_t _blns_param_scM1 = {{(limb_t *)_blns_param_scM1_limbs, 3, 0}};
static const limb_t _blns_param_scM2_limbs[] = {15002606599518648986UL, 13043305028329312333UL, 2UL};
static const int_t _blns_param_scM2 = {{(limb_t *)_blns_param_scM2_limbs, 3, 0}};
static const limb_t _blns_param_scM3_limbs[] = {454870099409846090UL, 403010299260651750UL, 1UL};
static const int_t _blns_param_scM3 = {{(limb_t *)_blns_param_scM3_limbs, 3, 0}};
static const limb_t _blns_param_scM4_limbs[] = {6117012463520434975UL, 402907032461738684UL, 1UL};
static const int_t _blns_param_scM4 = {{(limb_t *)_blns_param_scM4_limbs, 3, 0}};
static const limb_t _blns_param_stdev1sq_limbs[] = {169060907886838UL, 0UL};
static const int_t _blns_param_stdev1sq = {{(limb_t *)_blns_param_stdev1sq_limbs, 2, 0}};
static const limb_t _blns_param_stdev2sq_limbs[] = {40307261UL, 0UL};
static const int_t _blns_param_stdev2sq = {{(limb_t *)_blns_param_stdev2sq_limbs, 2, 0}};
static const limb_t _blns_param_stdev3sq_limbs[] = {660394171433UL, 0UL};
static const int_t _blns_param_stdev3sq = {{(limb_t *)_blns_param_stdev3sq_limbs, 2, 0}};
static const limb_t _blns_param_stdev4sq_limbs[] = {692473478704487465UL, 0UL};
static const int_t _blns_param_stdev4sq = {{(limb_t *)_blns_param_stdev4sq_limbs, 2, 0}};
static const limb_t _blns_param_inv2_limbs[] = {562949953421594UL};
static const int_t _blns_param_inv2 = {{(limb_t *)_blns_param_inv2_limbs, 1, 1}};
static const limb_t _blns_param_inv4_limbs[] = {281474976710797UL};
static const int_t _blns_param_inv4 = {{(limb_t *)_blns_param_inv4_limbs, 1, 1}};
static const unsigned int _blns_param_n[2] = {16, 16};
static const limb_t _blns_param_Bz3sqr_limbs[] = {454706217852438UL, 0UL};
static const int_t _blns_param_Bz3sqr = {{(limb_t *)_blns_param_Bz3sqr_limbs, 2, 0}};
static const limb_t _blns_param_Bz4_limbs[] = {13314398617UL};
static const int_t _blns_param_Bz4 = {{(limb_t *)_blns_param_Bz4_limbs, 1, 0}};
static const limb_t _blns_param_Pmodq_limbs[] = {42568471872UL};
static const int_t _blns_param_Pmodq = {{(limb_t *)_blns_param_Pmodq_limbs, 1, 1}};
static const limb_t _blns_param_l2Bsq0_limbs[] = {84695209UL};
static const int_t _blns_param_l2Bsq0 = {{(limb_t *)_blns_param_l2Bsq0_limbs, 1, 0}};
static const limb_t _blns_param_l2Bsq1_limbs[] = {7569UL};
static const int_t _blns_param_l2Bsq1 = {{(limb_t *)_blns_param_l2Bsq1_limbs, 1, 0}};
static const limb_t _blns_param_Ppmodq_0_limbs[] = {18068112UL};
static const int_t _blns_param_Ppmodq_0 = {{(limb_t *)_blns_param_Ppmodq_0_limbs, 1, 0}};
static const limb_t _blns_param_Ppmodq_1_limbs[] = {13089936UL};
static const int_t _blns_param_Ppmodq_1 = {{(limb_t *)_blns_param_Ppmodq_1_limbs, 1, 0}};
static const limb_t _blns_param_Ppmodq_2_limbs[] = {7661712UL};
static const int_t _blns_param_Ppmodq_2 = {{(limb_t *)_blns_param_Ppmodq_2_limbs, 1, 0}};
static const int_srcptr _blns_param_l2Bsq[] = {_blns_param_l2Bsq0, _blns_param_l2Bsq1};
static const int_srcptr _blns_param_Ppmodq[] = {_blns_param_Ppmodq_0, _blns_param_Ppmodq_1, _blns_param_Ppmodq_2};
static const polyring_t _blns_param_ring = {{_blns_param_q, 64, 51, 6, moduli_d64, 3, _blns_param_Pmodq, _blns_param_Ppmodq, _blns_param_inv2}};
static const dcompress_params_t _blns_param_dcomp = {{ _blns_param_q, _blns_param_qminus1, _blns_param_m, _blns_param_mby2, _blns_param_gamma, _blns_param_gammaby2, _blns_param_pow2D, _blns_param_pow2Dby2, 16, 0, 26 }};
static const abdlop_params_t _blns_param_tbox = {{ _blns_param_ring, _blns_param_dcomp, 34, 64, 0, 12, 20, _blns_param_Bsq, 1, 8, 5, 140, 1, 23, _blns_param_scM1, _blns_param_stdev1sq, 2, 12, _blns_param_scM2, _blns_param_stdev2sq}};
static const abdlop_params_t _blns_param_quad_eval_ = {{ _blns_param_ring, _blns_param_dcomp, 34, 64, 9, 3, 20, _blns_param_Bsq, 1, 8, 5, 140, 1, 23, _blns_param_scM1, _blns_param_stdev1sq, 2, 12, _blns_param_scM2, _blns_param_stdev2sq}};
static const abdlop_params_t _blns_param_quad_many_ = {{ _blns_param_ring, _blns_param_dcomp, 34, 64, 11, 1, 20, _blns_param_Bsq, 1, 8, 5, 140, 1, 23, _blns_param_scM1, _blns_param_stdev1sq, 2, 12, _blns_param_scM2, _blns_param_stdev2sq}};
static const lnp_quad_eval_params_t _blns_param_quad_eval = {{ _blns_param_quad_eval_, _blns_param_quad_many_, 4}};
static const lnp_tbox_params_t _blns_param = {{ _blns_param_tbox, _blns_param_quad_eval, 0, _blns_param_n, 8, 2, 34, 2, 19, _blns_param_scM3, _blns_param_stdev3sq, 2, 29, _blns_param_scM4, _blns_param_stdev4sq, _blns_param_Bz3sqr, _blns_param_Bz4, &_blns_param_l2Bsq[0], _blns_param_inv4, 26480UL }};

static const unsigned int blns_param_Es0[16] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const unsigned int blns_param_Es1[16] = {16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31};
static const unsigned int *blns_param_Es[2] = { blns_param_Es0, blns_param_Es1, };
static const unsigned int blns_param_Es_nrows[2] = {16, 16};

static const limb_t blns_param_p_limbs[] = {12289UL};
static const int_t blns_param_p = {{(limb_t *)blns_param_p_limbs, 1, 0}};
static const limb_t blns_param_pinv_limbs[] = {60834692663673UL};
static const int_t blns_param_pinv = {{(limb_t *)blns_param_pinv_limbs, 1, 0}};
static const unsigned int blns_param_s1_indices[4] = {0, 1, 2, 3};
static const lin_params_t blns_param = {{ _blns_param, 512, blns_param_p, blns_param_pinv, 8, blns_param_s1_indices, 4, NULL, 0,  NULL, 0, blns_param_Es, blns_param_Es_nrows, NULL, NULL }};

