// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-4)
// protocol is simulatable under MLWE(26,32,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(20,394,2^(35.94056))
// 
// Ring
// degree d = 64
// modulus q = 1099511627917, log(q) ~ 40.0
// factors q = q1
// 
// Compression
// D = 12
// gamma = 1695252, log(gamma) ~ 20.693068
// 
// Dimensions of secrets
// s1: m1 = 336
// m: l = 0
// s2: m2 = 58
// 
// Size of secrets
// l2(s1) <= alpha = 147.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 336)
// exact euclidean: no
// approximate infinity: yes (psi: 2558.1924, dimension: 8, bound: 10751.625)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 203161.6, log(stdev1/1.55) = 17.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 12697.6, log(stdev3/1.55) = 13.0
// stdev4 = 812646.4, log(stdev4/1.55) = 19.0
// 
// Repetition rate
// M1 = 3.8953296
// M2 = 2.465778
// M3 = 1.0227282
// M4 = 1.029934
// total = 10.117374
// 
// Security
// MSIS dimension: 20
// MSIS root hermite factor: 1.0043814
// MLWE dimension: 26
// MLWE root hermite factor: 1.0042737
// 
// Proof size
// ~ 70.5312500000000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937]
// bit length of products: [49, 99]
// inverses: [1, -162099428551732]

#include "lazer.h"
static const limb_t _p1_param_q_limbs[] = {1099511627917UL};
static const int_t _p1_param_q = {{(limb_t *)_p1_param_q_limbs, 1, 0}};
static const limb_t _p1_param_qminus1_limbs[] = {1099511627916UL};
static const int_t _p1_param_qminus1 = {{(limb_t *)_p1_param_qminus1_limbs, 1, 0}};
static const limb_t _p1_param_m_limbs[] = {648583UL};
static const int_t _p1_param_m = {{(limb_t *)_p1_param_m_limbs, 1, 0}};
static const limb_t _p1_param_mby2_limbs[] = {648583/2UL};
static const int_t _p1_param_mby2 = {{(limb_t *)_p1_param_mby2_limbs, 1, 0}};
static const limb_t _p1_param_gamma_limbs[] = {1695252UL};
static const int_t _p1_param_gamma = {{(limb_t *)_p1_param_gamma_limbs, 1, 0}};
static const limb_t _p1_param_gammaby2_limbs[] = {847626UL};
static const int_t _p1_param_gammaby2 = {{(limb_t *)_p1_param_gammaby2_limbs, 1, 0}};
static const limb_t _p1_param_pow2D_limbs[] = {4096UL};
static const int_t _p1_param_pow2D = {{(limb_t *)_p1_param_pow2D_limbs, 1, 0}};
static const limb_t _p1_param_pow2Dby2_limbs[] = {2048UL};
static const int_t _p1_param_pow2Dby2 = {{(limb_t *)_p1_param_pow2Dby2_limbs, 1, 0}};
static const limb_t _p1_param_Bsq_limbs[] = {1691728362685020UL, 0UL};
static const int_t _p1_param_Bsq = {{(limb_t *)_p1_param_Bsq_limbs, 2, 0}};
static const limb_t _p1_param_scM1_limbs[] = {2119613153584665101UL, 16515916402314107446UL, 3UL};
static const int_t _p1_param_scM1 = {{(limb_t *)_p1_param_scM1_limbs, 3, 0}};
static const limb_t _p1_param_scM2_limbs[] = {10189608724252333762UL, 8592086691763836887UL, 2UL};
static const int_t _p1_param_scM2 = {{(limb_t *)_p1_param_scM2_limbs, 3, 0}};
static const limb_t _p1_param_scM3_limbs[] = {9881459726603311366UL, 419261372266501503UL, 1UL};
static const int_t _p1_param_scM3 = {{(limb_t *)_p1_param_scM3_limbs, 3, 0}};
static const limb_t _p1_param_scM4_limbs[] = {2933309781762398636UL, 552185583227165551UL, 1UL};
static const int_t _p1_param_scM4 = {{(limb_t *)_p1_param_scM4_limbs, 3, 0}};
static const limb_t _p1_param_stdev1sq_limbs[] = {41274635715UL, 0UL};
static const int_t _p1_param_stdev1sq = {{(limb_t *)_p1_param_stdev1sq_limbs, 2, 0}};
static const limb_t _p1_param_stdev2sq_limbs[] = {40307261UL, 0UL};
static const int_t _p1_param_stdev2sq = {{(limb_t *)_p1_param_stdev2sq_limbs, 2, 0}};
static const limb_t _p1_param_stdev3sq_limbs[] = {161229046UL, 0UL};
static const int_t _p1_param_stdev3sq = {{(limb_t *)_p1_param_stdev3sq_limbs, 2, 0}};
static const limb_t _p1_param_stdev4sq_limbs[] = {660394171433UL, 0UL};
static const int_t _p1_param_stdev4sq = {{(limb_t *)_p1_param_stdev4sq_limbs, 2, 0}};
static const limb_t _p1_param_inv2_limbs[] = {549755813958UL};
static const int_t _p1_param_inv2 = {{(limb_t *)_p1_param_inv2_limbs, 1, 1}};
static const limb_t _p1_param_inv4_limbs[] = {274877906979UL};
static const int_t _p1_param_inv4 = {{(limb_t *)_p1_param_inv4_limbs, 1, 1}};
static const unsigned int _p1_param_n[0] = {};
static const limb_t _p1_param_Bz3sqr_limbs[] = {111012260217UL, 0UL};
static const int_t _p1_param_Bz3sqr = {{(limb_t *)_p1_param_Bz3sqr_limbs, 2, 0}};
static const limb_t _p1_param_Bz4_limbs[] = {13002342UL};
static const int_t _p1_param_Bz4 = {{(limb_t *)_p1_param_Bz4_limbs, 1, 0}};
static const limb_t _p1_param_Pmodq_limbs[] = {21498103425UL};
static const int_t _p1_param_Pmodq = {{(limb_t *)_p1_param_Pmodq_limbs, 1, 0}};
static const limb_t _p1_param_Ppmodq_0_limbs[] = {147071UL};
static const int_t _p1_param_Ppmodq_0 = {{(limb_t *)_p1_param_Ppmodq_0_limbs, 1, 1}};
static const limb_t _p1_param_Ppmodq_1_limbs[] = {146175UL};
static const int_t _p1_param_Ppmodq_1 = {{(limb_t *)_p1_param_Ppmodq_1_limbs, 1, 1}};
static const int_srcptr _p1_param_l2Bsq[] = {};
static const int_srcptr _p1_param_Ppmodq[] = {_p1_param_Ppmodq_0, _p1_param_Ppmodq_1};
static const polyring_t _p1_param_ring = {{_p1_param_q, 64, 41, 6, moduli_d64, 2, _p1_param_Pmodq, _p1_param_Ppmodq, _p1_param_inv2}};
static const dcompress_params_t _p1_param_dcomp = {{ _p1_param_q, _p1_param_qminus1, _p1_param_m, _p1_param_mby2, _p1_param_gamma, _p1_param_gammaby2, _p1_param_pow2D, _p1_param_pow2Dby2, 12, 1, 20 }};
static const abdlop_params_t _p1_param_tbox = {{ _p1_param_ring, _p1_param_dcomp, 336, 58, 0, 12, 20, _p1_param_Bsq, 1, 8, 5, 140, 1, 17, _p1_param_scM1, _p1_param_stdev1sq, 2, 12, _p1_param_scM2, _p1_param_stdev2sq}};
static const abdlop_params_t _p1_param_quad_eval_ = {{ _p1_param_ring, _p1_param_dcomp, 336, 58, 9, 3, 20, _p1_param_Bsq, 1, 8, 5, 140, 1, 17, _p1_param_scM1, _p1_param_stdev1sq, 2, 12, _p1_param_scM2, _p1_param_stdev2sq}};
static const abdlop_params_t _p1_param_quad_many_ = {{ _p1_param_ring, _p1_param_dcomp, 336, 58, 11, 1, 20, _p1_param_Bsq, 1, 8, 5, 140, 1, 17, _p1_param_scM1, _p1_param_stdev1sq, 2, 12, _p1_param_scM2, _p1_param_stdev2sq}};
static const lnp_quad_eval_params_t _p1_param_quad_eval = {{ _p1_param_quad_eval_, _p1_param_quad_many_, 4}};
static const lnp_tbox_params_t _p1_param = {{ _p1_param_tbox, _p1_param_quad_eval, 336, _p1_param_n, 8, 0, 336, 2, 13, _p1_param_scM3, _p1_param_stdev3sq, 2, 19, _p1_param_scM4, _p1_param_stdev4sq, _p1_param_Bz3sqr, _p1_param_Bz4, &_p1_param_l2Bsq[0], _p1_param_inv4, 72224UL }};

static const unsigned int p1_param_Ps[336] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335};

static const limb_t p1_param_p_limbs[] = {12289UL};
static const int_t p1_param_p = {{(limb_t *)p1_param_p_limbs, 1, 0}};
static const limb_t p1_param_pinv_limbs[] = {8410293191UL};
static const int_t p1_param_pinv = {{(limb_t *)p1_param_pinv_limbs, 1, 0}};
static const unsigned int p1_param_s1_indices[42] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41};
static const lin_params_t p1_param = {{ _p1_param, 512, p1_param_p, p1_param_pinv, 8, p1_param_s1_indices, 42, NULL, 0,  p1_param_Ps, 336, NULL, NULL, NULL, NULL }};

// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-4)
// protocol is simulatable under MLWE(33,43,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(15,308,2^(35.397879))
// 
// Ring
// degree d = 64
// modulus q = 4503599627371909, log(q) ~ 52.0
// factors q = q1
// 
// Compression
// D = 11
// gamma = 968478, log(gamma) ~ 19.88536
// 
// Dimensions of secrets
// s1: m1 = 232
// m: l = 16
// s2: m2 = 76
// 
// Size of secrets
// l2(s1) <= alpha = 122.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 232)
// exact euclidean: yes (dimensions: [16], bounds: [5833.9289])
// approximate infinity: yes (psi: 2433.5474, dimension: 8, bound: 46294293.0)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 203161.6, log(stdev1/1.55) = 17.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 406323.2, log(stdev3/1.55) = 18.0
// stdev4 = 3328599654.4, log(stdev4/1.55) = 31.0
// 
// Repetition rate
// M1 = 3.0963656
// M2 = 3.262833
// M3 = 1.035362
// M4 = 1.0331305
// total = 10.806735
// 
// Security
// MSIS dimension: 15
// MSIS root hermite factor: 1.004359
// MLWE dimension: 33
// MLWE root hermite factor: 1.004348
// 
// Proof size
// ~ 65.2792968750000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t _p2_param_q_limbs[] = {4503599627371909UL};
static const int_t _p2_param_q = {{(limb_t *)_p2_param_q_limbs, 1, 0}};
static const limb_t _p2_param_qminus1_limbs[] = {4503599627371908UL};
static const int_t _p2_param_qminus1 = {{(limb_t *)_p2_param_qminus1_limbs, 1, 0}};
static const limb_t _p2_param_m_limbs[] = {4650182686UL};
static const int_t _p2_param_m = {{(limb_t *)_p2_param_m_limbs, 1, 0}};
static const limb_t _p2_param_mby2_limbs[] = {2325091343UL};
static const int_t _p2_param_mby2 = {{(limb_t *)_p2_param_mby2_limbs, 1, 0}};
static const limb_t _p2_param_gamma_limbs[] = {968478UL};
static const int_t _p2_param_gamma = {{(limb_t *)_p2_param_gamma_limbs, 1, 0}};
static const limb_t _p2_param_gammaby2_limbs[] = {484239UL};
static const int_t _p2_param_gammaby2 = {{(limb_t *)_p2_param_gammaby2_limbs, 1, 0}};
static const limb_t _p2_param_pow2D_limbs[] = {2048UL};
static const int_t _p2_param_pow2D = {{(limb_t *)_p2_param_pow2D_limbs, 1, 0}};
static const limb_t _p2_param_pow2Dby2_limbs[] = {1024UL};
static const int_t _p2_param_pow2Dby2 = {{(limb_t *)_p2_param_pow2Dby2_limbs, 1, 0}};
static const limb_t _p2_param_Bsq_limbs[] = {402870327112506UL, 0UL};
static const int_t _p2_param_Bsq = {{(limb_t *)_p2_param_Bsq_limbs, 2, 0}};
static const limb_t _p2_param_scM1_limbs[] = {7468679340099591547UL, 1777631980325613655UL, 3UL};
static const int_t _p2_param_scM1 = {{(limb_t *)_p2_param_scM1_limbs, 3, 0}};
static const limb_t _p2_param_scM2_limbs[] = {15227696193531426347UL, 4848413748338640937UL, 3UL};
static const int_t _p2_param_scM2 = {{(limb_t *)_p2_param_scM2_limbs, 3, 0}};
static const limb_t _p2_param_scM3_limbs[] = {8570425630676290352UL, 652314234136136232UL, 1UL};
static const int_t _p2_param_scM3 = {{(limb_t *)_p2_param_scM3_limbs, 3, 0}};
static const limb_t _p2_param_scM4_limbs[] = {11680013831533779975UL, 611150577716046444UL, 1UL};
static const int_t _p2_param_scM4 = {{(limb_t *)_p2_param_scM4_limbs, 3, 0}};
static const limb_t _p2_param_stdev1sq_limbs[] = {41274635715UL, 0UL};
static const int_t _p2_param_stdev1sq = {{(limb_t *)_p2_param_stdev1sq_limbs, 2, 0}};
static const limb_t _p2_param_stdev2sq_limbs[] = {40307261UL, 0UL};
static const int_t _p2_param_stdev2sq = {{(limb_t *)_p2_param_stdev2sq_limbs, 2, 0}};
static const limb_t _p2_param_stdev3sq_limbs[] = {165098542858UL, 0UL};
static const int_t _p2_param_stdev3sq = {{(limb_t *)_p2_param_stdev3sq_limbs, 2, 0}};
static const limb_t _p2_param_stdev4sq_limbs[] = {11079575659271799439UL, 0UL};
static const int_t _p2_param_stdev4sq = {{(limb_t *)_p2_param_stdev4sq_limbs, 2, 0}};
static const limb_t _p2_param_inv2_limbs[] = {2251799813685954UL};
static const int_t _p2_param_inv2 = {{(limb_t *)_p2_param_inv2_limbs, 1, 1}};
static const limb_t _p2_param_inv4_limbs[] = {1125899906842977UL};
static const int_t _p2_param_inv4 = {{(limb_t *)_p2_param_inv4_limbs, 1, 1}};
static const unsigned int _p2_param_n[1] = {16};
static const limb_t _p2_param_Bz3sqr_limbs[] = {113676554463109UL, 0UL};
static const int_t _p2_param_Bz3sqr = {{(limb_t *)_p2_param_Bz3sqr_limbs, 2, 0}};
static const limb_t _p2_param_Bz4_limbs[] = {53257594470UL};
static const int_t _p2_param_Bz4 = {{(limb_t *)_p2_param_Bz4_limbs, 1, 0}};
static const limb_t _p2_param_Pmodq_limbs[] = {914758834844557UL};
static const int_t _p2_param_Pmodq = {{(limb_t *)_p2_param_Pmodq_limbs, 1, 0}};
static const limb_t _p2_param_l2Bsq0_limbs[] = {34034726UL};
static const int_t _p2_param_l2Bsq0 = {{(limb_t *)_p2_param_l2Bsq0_limbs, 1, 0}};
static const limb_t _p2_param_Ppmodq_0_limbs[] = {844424946380089UL};
static const int_t _p2_param_Ppmodq_0 = {{(limb_t *)_p2_param_Ppmodq_0_limbs, 1, 0}};
static const limb_t _p2_param_Ppmodq_1_limbs[] = {844424941591641UL};
static const int_t _p2_param_Ppmodq_1 = {{(limb_t *)_p2_param_Ppmodq_1_limbs, 1, 0}};
static const limb_t _p2_param_Ppmodq_2_limbs[] = {844424936651289UL};
static const int_t _p2_param_Ppmodq_2 = {{(limb_t *)_p2_param_Ppmodq_2_limbs, 1, 0}};
static const int_srcptr _p2_param_l2Bsq[] = {_p2_param_l2Bsq0};
static const int_srcptr _p2_param_Ppmodq[] = {_p2_param_Ppmodq_0, _p2_param_Ppmodq_1, _p2_param_Ppmodq_2};
static const polyring_t _p2_param_ring = {{_p2_param_q, 64, 53, 6, moduli_d64, 3, _p2_param_Pmodq, _p2_param_Ppmodq, _p2_param_inv2}};
static const dcompress_params_t _p2_param_dcomp = {{ _p2_param_q, _p2_param_qminus1, _p2_param_m, _p2_param_mby2, _p2_param_gamma, _p2_param_gammaby2, _p2_param_pow2D, _p2_param_pow2Dby2, 11, 0, 33 }};
static const abdlop_params_t _p2_param_tbox = {{ _p2_param_ring, _p2_param_dcomp, 233, 76, 16, 12, 15, _p2_param_Bsq, 1, 8, 5, 140, 1, 17, _p2_param_scM1, _p2_param_stdev1sq, 2, 12, _p2_param_scM2, _p2_param_stdev2sq}};
static const abdlop_params_t _p2_param_quad_eval_ = {{ _p2_param_ring, _p2_param_dcomp, 233, 76, 25, 3, 15, _p2_param_Bsq, 1, 8, 5, 140, 1, 17, _p2_param_scM1, _p2_param_stdev1sq, 2, 12, _p2_param_scM2, _p2_param_stdev2sq}};
static const abdlop_params_t _p2_param_quad_many_ = {{ _p2_param_ring, _p2_param_dcomp, 233, 76, 27, 1, 15, _p2_param_Bsq, 1, 8, 5, 140, 1, 17, _p2_param_scM1, _p2_param_stdev1sq, 2, 12, _p2_param_scM2, _p2_param_stdev2sq}};
static const lnp_quad_eval_params_t _p2_param_quad_eval = {{ _p2_param_quad_eval_, _p2_param_quad_many_, 4}};
static const lnp_tbox_params_t _p2_param = {{ _p2_param_tbox, _p2_param_quad_eval, 232, _p2_param_n, 8, 1, 249, 2, 18, _p2_param_scM3, _p2_param_stdev3sq, 2, 31, _p2_param_scM4, _p2_param_stdev4sq, _p2_param_Bz3sqr, _p2_param_Bz4, &_p2_param_l2Bsq[0], _p2_param_inv4, 66846UL }};

static const unsigned int p2_param_Ps[232] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231};
static const unsigned int p2_param_Em0[16] = {232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247};
static const unsigned int *p2_param_Em[1] = { p2_param_Em0, };
static const unsigned int p2_param_Em_nrows[1] = {16};
static const unsigned int p2_param_m_indices[2] = {28, 29};

static const limb_t p2_param_p_limbs[] = {12289UL};
static const int_t p2_param_p = {{(limb_t *)p2_param_p_limbs, 1, 0}};
static const limb_t p2_param_pinv_limbs[] = {1137535458000033UL};
static const int_t p2_param_pinv = {{(limb_t *)p2_param_pinv_limbs, 1, 0}};
static const unsigned int p2_param_s1_indices[29] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 30};
static const lin_params_t p2_param = {{ _p2_param, 512, p2_param_p, p2_param_pinv, 8, p2_param_s1_indices, 29, p2_param_m_indices, 2,  p2_param_Ps, 232, NULL, NULL, p2_param_Em, p2_param_Em_nrows }};

